name: libretrack
description: Private, cross-platform package tracking app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+3

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  animate_icons: ^2.0.0
  backdrop: ^0.6.0
  barcode_widget: ^2.0.0
  bloc: ^7.0.0
  collection: ^1.15.0
  connectivity_plus: ^1.0.6
  cupertino_icons: ^1.0.2
  device_info_plus: ^2.1.0
  devicelocale: ^0.4.1
  diffutil_sliverlist: ^0.5.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  expandable_page_view: ^1.0.4
  floor: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_linkify: ^5.0.0
  flutter_local_notifications: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_mailer: ^2.0.0
  flutter_secure_storage: ^4.1.0
  flutter_staggered_animations: ^1.0.0
  fluttertoast: ^8.0.3
  freezed_annotation: ^0.14.2
  http: ^0.13.0
  injectable: ^1.4.1
  jiffy: ^4.0.0
  json_serializable: ^4.1.4
  logger: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info_plus: ^1.0.1
  quiver: ^3.0.0
  receive_sharing_intent: ^1.4.5
  responsive_builder: ^0.4.1
  share_plus: ^2.1.2
  shared_preferences: ^2.0.4
  smooth_page_indicator: ^0.3.0-nullsafety.0
  superellipse_shape: ^0.2.0-nullsafety.0
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  workmanager: ^0.4.0
  xml: ^5.1.2

dev_dependencies:
  analyzer: ^1.5.0
  bloc_test: ^8.1.0
  build_runner: ^2.0.1
  device_preview: ^0.7.1
  floor_generator: ^1.1.0
  flutter_lints: ^1.0.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  intl_utils: ^2.1.0
  mocktail: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/service_logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: AppLogo
      fonts:
        - asset: fonts/AppLogo.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
